name: Build Raphael 5.4

on:
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-22.04

steps:
  - name: Install packages
    run: |
      sudo apt update
      sudo apt install -y \
      git curl wget flex bison bc cpio \
      zip unzip rsync build-essential \
      libssl-dev libelf-dev

  - name: Clone kernel
    run: |
      git clone --depth=1 \
      https://github.com/Nyako-mini/raphael5-4-resukisu.git kernel

  - name: Download toolchains
    run: |
      mkdir tc
      cd tc

      wget -q https://github.com/ravindu644/Android-Kernel-Tutorials/releases/download/toolchains/llvm-arm-toolchain-ship-10.0.9.tar.gz
      wget -q https://github.com/ravindu644/Android-Kernel-Tutorials/releases/download/toolchains/aarch64-linux-android-4.9-Linux-5.4.tar.gz

      tar -xf llvm-arm-toolchain-ship-10.0.9.tar.gz
      tar -xf aarch64-linux-android-4.9-Linux-5.4.tar.gz

  - name: Set build info
    run: |
      echo 'KBUILD_BUILD_USER=voxelsy' >> $GITHUB_ENV
      echo 'KBUILD_BUILD_HOST=ubuntu' >> $GITHUB_ENV
      echo 'LOCALVERSION=-qgki' >> $GITHUB_ENV

  - name: Build kernel
    run: |
      export PATH=$GITHUB_WORKSPACE/tc/llvm-arm-toolchain-ship-10.0.9/bin:$PATH
      export PATH=$GITHUB_WORKSPACE/tc/aarch64-linux-android-4.9/bin:$PATH

      cd kernel

      mkdir -p out

      DEFCONFIG=$(find arch/arm64/configs -iname '*raphael*defconfig' | head -n1 | xargs basename)

      make O=out ARCH=arm64 $DEFCONFIG

      make -j$(nproc) \
      O=out \
      ARCH=arm64 \
      CC=clang \
      LLVM=1 \
      LLVM_IAS=1 \
      CROSS_COMPILE=aarch64-linux-android- \
      CROSS_COMPILE_ARM32=arm-linux-androideabi-

  - name: Upload
    uses: actions/upload-artifact@v4
    with:
      name: raphael-kernel
      path: |
        kernel/out/arch/arm64/boot/Image*
        kernel/out/arch/arm64/boot/*.dtb
        kernel/out/arch/arm64/boot/*.img
